# ===============================================================
# 根据如下的配置说明完善自己的站点配置，建议另外拷贝进行调整避免冲突
# Improve your site configuration according to the following 
# configuration instructions. It is recommended to make 
# additional copies for adjustment to avoid conflicts
# ===============================================================

# ---------------------------------------------------------------
# Hugo 引擎的基础配置
# Basic configure for Hugo engine 
# ---------------------------------------------------------------

# 站点域名，比如： https://hugo-next.eu.org
# Website domain, eg: https://hugo-next.eu.org
baseURL: /
# 站点标题
# Website title
title: Hugo NexT
# 主题名称
# Theme name
theme: hugo-theme-next
# 站点默认的语言和代码
# Default language & code for website
defaultContentLanguage: zh-cn
languageCode: zh-CN
# 是否包含中文，日语，韩文
# Whether contains Chinese, Japanese and Korean
hasCJKLanguage: true
# 每页显示文章数量
# Display items per page
pagination:
  pagerSize: 10
# 开启支持表情符号
# Enable Emoji support
enableEmoji: true
# 让 Markdown 文档支持 HTML 语法，高亮，文章目录等功能
# Make markdown content support HTML syntax, highlight, toc etc.
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  tableOfContents:
    # 开始/结束标题级别：1-6 (建议从2开始)
    # Heading title level of start or end: 1-6
    # Recommended start level: 2
    startLevel: 2
    endLevel: 4

# 站点文章导航文件
# Site map of all articles
sitemap:
  filename: "sitemap.xml"
  changefreq: "weekly"
  priority: 0.5

outputFormats:
  RSS:
    baseName: "rss"
  # 自定义生成本地搜索文件
  # Custom file of indexes for local search
  LocalIndexes:
    mediaType: application/xml
    baseName: searchindexes
    isPlainText: true
    notAlternative: true
  # 生成 Algolia 索引文件
  # Build indexes of Aloglia
  AlgoliaIndexes:
    mediaType: application/json
    baseName: algolia
    isPlainText: true
    notAlternative: true

# 默认使用本地搜索，如切换到 Algolia 搜索引擎，
# 请将下面的 LocalIndexes 替换成 AlgoliaIndexes
# By default use local search, before switch to Algolia engine
# Please replace LocalIndexes with AlgoliaIndexes
outputs:
  home: ["HTML", "RSS", "LocalIndexes"]

# 输出 robots 文件支持爬虫扫描
# Enable robots with support crawler scan
enableRobotsTXT: true

# 强制输出时压缩文件
# Compress all files when output
minify:
  minifyOutput: true
  